refactored readme according release
Gifford47/HCPBridgeMqtt pull request #41
Opened 2023-08-30 14:06 UTC by Gifford47

The old readme was a little bit unclear und a lot of informations was missing. I tried to summarize all info that i currently have. Feel free to add as much info as you have :)

2023-08-30 14:07 UTC, Gifford47 commented
the info from discussion #38 has to be added also

2023-08-31 12:19 UTC, kfroeschl requested changes
looks good and well structured 👍

Only some images do not show

2023-08-31 12:19 UTC, kfroeschl commented on README.md
> +![alt text](Images/webinterface.png)
Link is not working - filename is case sensitive
Images/webinterface.PNG

2023-08-31 12:19 UTC, kfroeschl commented on README.md
> +![Homeassistant card2](Images/ha.png)
wrong filename again
Images/HA.png

2023-09-01 06:53 UTC, Gifford47 commented
could someone provide a new pic from the webinterface with the configuration tab?

2023-09-01 06:59 UTC, Tysonpower commented
> could someone provide a new pic from the webinterface with the configuration tab?

here it is:

![image](https://github.com/Gifford47/HCPBridgeMqtt/assets/13482963/96063836-dcae-4c56-a02f-b8fae15fb5ca)

2023-10-22 12:53 UTC, Gifford47 reviewed
all fine

2023-10-22 13:09 UTC, merged